[manager]
prepend_keymap = [
	{ on = [ "s", "f" ], run = 'search fd --args="--hidden"' },
	{ on = [ "s", "g" ], run = 'search rg --args="--hidden"' },
	{ on = "s", run = 'noop' },
	{ on = "S", run = 'noop' },
]
